#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
readme = ROOT / "README.md"
service_paths = [
    ROOT / "services/web/README.md",
    ROOT / "services/worker-cv/README.md",
    ROOT / "services/worker-ocr/README.md",
    ROOT / "services/worker-metadata/README.md",
    ROOT / "services/worker-export/README.md",
    ROOT / "services/llm-gateway/README.md",
]

begin = "<!-- BEGIN IMPORTED SERVICE READMES -->"
end = "<!-- END IMPORTED SERVICE READMES -->"

body = readme.read_text(encoding="utf-8")

parts = [begin, "", "## Imported Service READMEs", "", "This section is generated by `scripts/dev/sync_root_readme.py`.", ""]
for p in service_paths:
    rel = p.relative_to(ROOT)
    parts.append(f"### Source: `{rel}`")
    parts.append("")
    parts.append(p.read_text(encoding="utf-8").strip())
    parts.append("")
parts.append(end)
new_section = "\n".join(parts)

if begin in body and end in body:
    start = body.index(begin)
    finish = body.index(end) + len(end)
    updated = body[:start] + new_section + body[finish:]
else:
    updated = body.rstrip() + "\n\n" + new_section + "\n"

readme.write_text(updated, encoding="utf-8")
